In [52]:
import numpy as np
from scipy.special import expit as activation_function
from scipy.stats import truncnorm

In [53]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [54]:
df = pd.read_csv ("C:/Users/Aparna Akula/Documents/Machine Learning/numeric_with_label.csv")
df.head()

Altitude  Number_of_Bags  Bag_Weight  Aroma  Flavor  Aftertaste  Acidity  \
0      1800             150        60.0   7.33    7.58        7.83     7.75   
1       890             320        60.0   7.50    7.75        7.58     7.50   
2       890             320        60.0   7.67    7.67        7.58     7.75   
3       890             320        60.0   7.67    7.83        7.50     7.67   
4       890             320        60.0   7.58    7.67        7.58     7.58   

   Body  Balance  Uniformity  Clean_Cup  Sweetness  Total_Cup_Points  \
0  7.75     7.92        10.0       10.0       10.0             84.33   
1  7.58     7.50        10.0       10.0       10.0             83.92   
2  7.67     7.67        10.0       10.0       10.0             83.75   
3  7.67     7.50        10.0       10.0       10.0             83.67   
4  7.67     7.58        10.0       10.0       10.0             83.58   

   Moisture  Quakers  Category_Two_Defects  Category_One_Defects  \
0      0.11        0                     4                     0   
1      0.00        0                     3                     0   
2      0.11        0                     5                     0   
3      0.11        0                     2                     0   
4      0.11        0                     5                     0   

  Processing_Method  
0      Washed / Wet  
1     Natural / Dry  
2     Natural / Dry  
3     Natural / Dry  
4     Natural / Dry

In [55]:
!pip install tensorflow

In [56]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.math import confusion_matrix

In [57]:
target_column = ['Processing_Method']
predictors = list(set(list(df.columns)) - set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe()

Altitude  Number_of_Bags  Bag_Weight       Aroma      Flavor  \
count  570.000000      570.000000  570.000000  570.000000  570.000000   
mean     0.255215        0.276290    0.462053    0.864449    0.866270   
std      0.179904        0.237716    0.373589    0.033523    0.035502   
min      0.000164        0.001818    0.000000    0.723429    0.730104   
25%      0.163934        0.027273    0.025000    0.848000    0.845444   
50%      0.213115        0.258182    0.750000    0.866286    0.865052   
75%      0.278689        0.500000    0.750000    0.885714    0.884660   
max      1.000000        1.000000    1.000000    1.000000    1.000000   

       Aftertaste     Acidity        Body     Balance  Uniformity   Clean_Cup  \
count  570.000000  570.000000  570.000000  570.000000  570.000000  570.000000   
mean     0.867488    0.875980    0.888753    0.871566    0.986418    0.985137   
std      0.036832    0.033056    0.031192    0.036974    0.047129    0.071954   
min      0.744706    0.728438    0.751781    0.708625    0.600000    0.133000   
25%      0.843529    0.854312    0.870546    0.854312    1.000000    1.000000   
50%      0.872941    0.874126    0.890736    0.874126    1.000000    1.000000   
75%      0.891765    0.893939    0.910926    0.893939    1.000000    1.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

        Sweetness  Total_Cup_Points    Moisture     Quakers  \
count  570.000000        570.000000  570.000000  570.000000   
mean     0.992153          0.912075    0.577606    0.019777   
std      0.049944          0.028669    0.230019    0.082537   
min      0.133000          0.665369    0.000000    0.000000   
25%      1.000000          0.902691    0.588235    0.000000   
50%      1.000000          0.915592    0.647059    0.000000   
75%      1.000000          0.926713    0.705882    0.000000   
max      1.000000          1.000000    1.000000    1.000000   

       Category_Two_Defects  Category_One_Defects  
count            570.000000            570.000000  
mean               0.077641              0.013243  
std                0.114470              0.076498  
min                0.000000              0.000000  
25%                0.000000              0.000000  
50%                0.042553              0.000000  
75%                0.106383              0.000000  
max                1.000000              1.000000

In [58]:
df['Processing_Method'] = df['Processing_Method'].astype('category')
# Assigning numerical values and storing in another column
df['Processing_Method'] = df['Processing_Method'].cat.codes

In [59]:
y = df['Processing_Method'].values
X = df[predictors].values

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(399, 17)
(171, 17)


In [61]:
y_train = to_categorical(y_train, 5)
y_test = to_categorical(y_test, 5)

In [62]:
model = Sequential()
model.add(Dense(15, input_dim=17, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(5, activation='softmax'))

In [63]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [64]:
model.fit(X_train, y_train, epochs=25)

Epoch 1/25
13/13 [==============================] - 2s 4ms/step - loss: 1.5968 - accuracy: 0.1153
Epoch 2/25
13/13 [==============================] - 0s 2ms/step - loss: 1.4770 - accuracy: 0.1704
Epoch 3/25
13/13 [==============================] - 0s 2ms/step - loss: 1.3522 - accuracy: 0.1880
Epoch 4/25
13/13 [==============================] - 0s 2ms/step - loss: 1.2063 - accuracy: 0.2707
Epoch 5/25
13/13 [==============================] - 0s 2ms/step - loss: 1.0554 - accuracy: 0.6992
Epoch 6/25
13/13 [==============================] - 0s 2ms/step - loss: 0.9400 - accuracy: 0.6992
Epoch 7/25
13/13 [==============================] - 0s 2ms/step - loss: 0.9106 - accuracy: 0.6992
Epoch 8/25
13/13 [==============================] - 0s 2ms/step - loss: 0.9033 - accuracy: 0.6992
Epoch 9/25
13/13 [==============================] - 0s 2ms/step - loss: 0.9028 - accuracy: 0.6992
Epoch 10/25
13/13 [==============================] - 0s 2ms/step - loss: 0.9016 - accuracy: 0.6992
Epoch 11/25
13/13 [

In [65]:
pred_train= model.predict(X_train)
scores = model.evaluate(X_train, y_train, verbose=0)
print('Accuracy on training data: {}% \n Error on training data: {}'.format(scores[1], 1 - scores[1]))   
 
pred_test= model.predict(X_test)
scores2 = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy on test data: {}% \n Error on test data: {}'.format(scores2[1], 1 - scores2[1]))    

13/13 [==============================] - 0s 3ms/step
Accuracy on training data: 0.6992481350898743% 
 Error on training data: 0.30075186491012573
6/6 [==============================] - 0s 2ms/step
Accuracy on test data: 0.7017543911933899% 
 Error on test data: 0.2982456088066101


In [66]:
y_test

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.

In [67]:
pred_test

array([[0.2107585 , 0.0331086 , 0.01116286, 0.05692646, 0.6880436 ],
       [0.22818327, 0.03554793, 0.01309855, 0.0623435 , 0.66082674],
       [0.16742714, 0.02853283, 0.00900558, 0.07493153, 0.72010285],
       [0.15116172, 0.02400414, 0.00611119, 0.04273565, 0.77598727],
       [0.20443064, 0.03085491, 0.01001905, 0.05548465, 0.6992107 ],
       [0.19553982, 0.03372445, 0.01091894, 0.06038417, 0.6994326 ],
       [0.1872191 , 0.02921446, 0.0094171 , 0.06239592, 0.71175337],
       [0.1487592 , 0.02288316, 0.00589273, 0.04599208, 0.77647287],
       [0.21101046, 0.04140779, 0.01542587, 0.07762055, 0.6545354 ],
       [0.18902636, 0.0364111 , 0.01184995, 0.06629907, 0.6964135 ],
       [0.22279635, 0.04748233, 0.01678539, 0.06376848, 0.6491675 ],
       [0.19756113, 0.03436827, 0.01103025, 0.05630015, 0.7007402 ],
       [0.19471471, 0.03430086, 0.01048453, 0.05233256, 0.7081674 ],
       [0.18163934, 0.03398104, 0.01157859, 0.07955361, 0.69324744],
       [0.14734094, 0.02170157, 0.

In [68]:
row_maxes = pred_test.max(axis=1).reshape(-1, 1)
np.where(pred_test == row_maxes, 1, 0)
#np.where(pred_test == row_maxes).astype(int)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0,

In [69]:
pred_test[:] = np.where(pred_test == row_maxes, 1, 0)

In [70]:
pred_test

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0.

In [71]:
pred_test = pd.DataFrame(pred_test, columns = [0,1,2,3,4])
y_test = pd.DataFrame(y_test, columns = [0,1,2,3,4]) 

In [76]:
y_test_array

0      0
1      0
2      4
3      4
4      4
      ..
166    4
167    4
168    0
169    4
170    4
Length: 171, dtype: int64

In [74]:
pred = pred_test.idxmax(1)
y_test_array = y_test.idxmax(1)

In [77]:
print("confusion matrix : ", confusion_matrix(y_test_array,pred))


confusion matrix :  tf.Tensor(
[[  0   0   0   0  31]
 [  0   0   0   0   5]
 [  0   0   0   0   4]
 [  0   0   0   0  11]
 [  0   0   0   0 120]], shape=(5, 5), dtype=int32)
